[2022-03-06 04:18:41,422] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: spotify_dag.whole_spotify_etl manual__2022-03-06T04:18:35.661077+00:00 [queued]>
[2022-03-06 04:18:41,495] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: spotify_dag.whole_spotify_etl manual__2022-03-06T04:18:35.661077+00:00 [queued]>
[2022-03-06 04:18:41,496] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-06 04:18:41,497] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-03-06 04:18:41,497] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-06 04:18:41,601] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): whole_spotify_etl> on 2022-03-06 04:18:35.661077+00:00
[2022-03-06 04:18:41,641] {standard_task_runner.py:52} INFO - Started process 536 to run task
[2022-03-06 04:18:41,778] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'spotify_dag', 'whole_spotify_etl', 'manual__2022-03-06T04:18:35.661077+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/spotify_dag.py', '--cfg-path', '/tmp/tmp5eumjhcu', '--error-file', '/tmp/tmp3n8w75fs']
[2022-03-06 04:18:41,802] {standard_task_runner.py:77} INFO - Job 5: Subtask whole_spotify_etl
[2022-03-06 04:18:42,781] {logging_mixin.py:109} INFO - Running <TaskInstance: spotify_dag.whole_spotify_etl manual__2022-03-06T04:18:35.661077+00:00 [running]> on host 320d3876a6f4
[2022-03-06 04:18:43,066] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ing.jlllopezp@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spotify_dag
AIRFLOW_CTX_TASK_ID=whole_spotify_etl
AIRFLOW_CTX_EXECUTION_DATE=2022-03-06T04:18:35.661077+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-06T04:18:35.661077+00:00
[2022-03-06 04:19:03,043] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/spotify_etl.py", line 64, in run_spotify_etl
    with open('../misc/token.txt', 'w') as file:
FileNotFoundError: [Errno 2] No such file or directory: '../misc/token.txt'
[2022-03-06 04:19:03,263] {taskinstance.py:1282} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_dag, task_id=whole_spotify_etl, execution_date=20220306T041835, start_date=20220306T041841, end_date=20220306T041903
[2022-03-06 04:19:03,398] {standard_task_runner.py:92} ERROR - Failed to execute job 5 for task whole_spotify_etl
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/spotify_etl.py", line 64, in run_spotify_etl
    with open('../misc/token.txt', 'w') as file:
FileNotFoundError: [Errno 2] No such file or directory: '../misc/token.txt'
[2022-03-06 04:19:03,485] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-06 04:19:04,433] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
